# Generated by Django 5.0.3 on 2025-01-13 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('installed', models.BooleanField(default=False)),
                ('verbal', models.BooleanField(default=False)),
                ('invoice', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('stale', models.BooleanField(default=False)),
                ('probable', models.BooleanField(default=False)),
                ('trial', models.BooleanField(default=False)),
                ('trial_expiration', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
